services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: intelsent-api:latest
    container_name: intelsent-api
    command: uvicorn serving.api:app --host 0.0.0.0 --port 8000
    depends_on:
      pgvector:
        condition: service_healthy
      intelsent-redis:
        condition: service_healthy
    environment:
      APP_CONFIG: /app/config/app.yaml
      HF_HOME: /app/.cache/hf
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: gpt-4o-mini
      NO_OPENAI: ${NO_OPENAI:-${OPENAI_API_KEY:+0}}
      REDIS_URL: redis://intelsent-redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./config/app.docker.yml:/app/config/app.yaml:ro
      - ./config/drivers.yml:/app/config/drivers.yml:ro
      - ./data:/app/data:ro

  pgvector:
    image: ankane/pgvector:latest
    container_name: intel_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: intel
      POSTGRES_PASSWORD: intel
      POSTGRES_DB: intelrag
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intel -d intelrag"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
