services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: intelsent-api:latest
    container_name: intelsent-api
    depends_on:
      pgvector:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      APP_CONFIG: /app/config/app.yaml
      HF_HOME: /app/.cache/hf
      SENTENCE_TRANSFORMERS_HOME: /app/.cache/sentence-transformers
      # optional: suppress general FutureWarnings from transformers
      PYTHONWARNINGS: "ignore::FutureWarning:transformers"
    volumes:
      - ./config/app.docker.yml:/app/config/app.yaml:ro
      - ./config/drivers.yml:/app/config/drivers.yml:ro
    command: >
      sh -lc '
        unset TRANSFORMERS_CACHE
        exec uvicorn serving.api:app --host 0.0.0.0 --port 8000 --log-level info
      '
