services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intel_api
    ports:
      - "8000:8000"
    depends_on:
      - pgvector
    networks:
      - default
    volumes:
      # Use the actual filename we have: app.docker.yml (NOT .yaml)
      - ./config/app.docker.yml:/app/config/app.yaml:ro
      - ./config/drivers.yml:/app/config/drivers.yml:ro
