artifacts_dir: artifacts

embedding:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  device: cpu

retrieval:
  top_k: 10
  max_k: 10

generation:
  max_context_chars: 8000
  model: gpt-4o-mini
  use_openai: false

rerank:
  enabled: false
  model_name: cross-encoder/ms-marco-MiniLM-L-6-v2

pgvector:
  enabled: true
  conn: postgresql://<NEON_USER>:<NEON_PASS>@<NEON_HOST>/<NEON_DB>  # placeholder ONLY
  table: chunks
  text_col: text
