
artifacts_dir: "artifacts"

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "mps"   # or "cpu" if you prefer

retrieval:
  top_k: 5
  max_k: 10

generation:
  max_context_chars: 6000

rerank:
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
