apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelsent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelsent-api
  template:
    metadata:
      labels:
        app: intelsent-api
    spec:
      containers:
        - name: api
          image: intelsent-api:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: HF_HOME
              value: /app/.cache/hf
            - name: TRANSFORMERS_CACHE
              value: /app/.cache/transformers
            - name: SENTENCE_TRANSFORMERS_HOME
              value: /app/.cache/sentence-transformers
            - name: TRANSFORMERS_OFFLINE
              value: "1"
          volumeMounts:
            - name: app-config
              mountPath: /app/config/app.yaml
              subPath: app.yaml
              readOnly: true
            - name: app-config
              mountPath: /app/config/drivers.yml
              subPath: drivers.yml
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
      volumes:
        - name: app-config
          configMap:
            name: intelsent-config
---
apiVersion: v1
kind: Service
metadata:
  name: intelsent-api
spec:
  selector:
    app: intelsent-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
