name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements-api.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        env:
          SKIP_CHAIN_INIT: "1"
        run: pytest -q --maxfail=1 --disable-warnings
